# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "zh-TW"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  review_details: true
  review_progress: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 0
    drafts: true
chat:
  auto_reply: true
knowledge_base:
  code_guidelines:
    enabled: true
