Set-StrictMode -Version Latest

function Get-BraintrustJsonProperty {
    param([Parameter(Mandatory = $true)][object]$Object,[Parameter(Mandatory = $true)][string]$Name)
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) { return $null }
    return $property
}
function Test-BraintrustJsonObjectValue { param([object]$Value) if ($null -eq $Value){return $false}; if($Value -is [System.Collections.IDictionary]){return $true}; return ($Value -is [pscustomobject]) }
function Assert-BraintrustJsonObjectValue { param([Parameter(Mandatory=$true)][AllowNull()][object]$Value,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath) if(-not(Test-BraintrustJsonObjectValue $Value)){ $t=if($null-eq$Value){'null'}else{$Value.GetType().FullName}; throw "JSON field '$FieldPath' must be an object; actual type was '$t'. Scalar/array coercion is forbidden."}; return $Value }
function Get-BraintrustRequiredJsonObject { param([Parameter(Mandatory=$true)][object]$Object,[Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath) $p=Get-BraintrustJsonProperty $Object $Name; if($null-eq$p){throw "Missing required JSON object '$FieldPath'."}; return Assert-BraintrustJsonObjectValue $p.Value $FieldPath }
function Get-BraintrustRequiredJsonBoolean { param([Parameter(Mandatory=$true)][object]$Object,[Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath) $p=Get-BraintrustJsonProperty $Object $Name; if($null-eq$p){throw "Missing required JSON boolean '$FieldPath'."}; if($p.Value -isnot [bool]){ $t=if($null-eq$p.Value){'null'}else{$p.Value.GetType().FullName}; throw "JSON field '$FieldPath' must be a boolean; actual type was '$t'. String/numeric coercion is forbidden."}; return [bool]$p.Value }
function Get-BraintrustRequiredJsonString { param([Parameter(Mandatory=$true)][object]$Object,[Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath,[switch]$AllowEmpty) $p=Get-BraintrustJsonProperty $Object $Name; if($null-eq$p){throw "Missing required JSON string '$FieldPath'."}; if($p.Value -isnot [string]){ $t=if($null-eq$p.Value){'null'}else{$p.Value.GetType().FullName}; throw "JSON field '$FieldPath' must be a string; actual type was '$t'."}; $v=[string]$p.Value; if(-not$AllowEmpty -and [string]::IsNullOrWhiteSpace($v)){throw "JSON field '$FieldPath' must be a non-empty string."}; return $v }
function Get-BraintrustRequiredJsonTimestampString { param([Parameter(Mandatory=$true)][object]$Object,[Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath) $p=Get-BraintrustJsonProperty $Object $Name; if($null-eq$p){throw "Missing required JSON timestamp string '$FieldPath'."}; if($p.Value -is [string]){return [string]$p.Value}; if($p.Value -is [DateTimeOffset]){return ([DateTimeOffset]$p.Value).ToUniversalTime().ToString('o')}; if($p.Value -is [DateTime]){ $d=[DateTime]$p.Value; if($d.Kind -eq [DateTimeKind]::Unspecified){$d=[DateTime]::SpecifyKind($d,[DateTimeKind]::Local)}; return $d.ToUniversalTime().ToString('o')}; throw "JSON field '$FieldPath' must originate from an ISO-8601 JSON string." }
function Test-BraintrustJsonNumericClrType { param([object]$Value) if($null-eq$Value){return $false}; return ($Value -is [byte] -or $Value -is [sbyte] -or $Value -is [int16] -or $Value -is [uint16] -or $Value -is [int32] -or $Value -is [uint32] -or $Value -is [int64] -or $Value -is [uint64] -or $Value -is [single] -or $Value -is [double] -or $Value -is [decimal]) }
function ConvertTo-BraintrustFiniteDecimal { param([Parameter(Mandatory=$true)][object]$Value,[Parameter(Mandatory=$true)][string]$FieldPath) if(-not(Test-BraintrustJsonNumericClrType $Value)){throw "JSON field '$FieldPath' must be a JSON number."}; return [decimal]$Value }
function Get-BraintrustRequiredJsonFiniteNumber { param([Parameter(Mandatory=$true)][object]$Object,[Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath) $p=Get-BraintrustJsonProperty $Object $Name; if($null-eq$p){throw "Missing required JSON number '$FieldPath'."}; return ConvertTo-BraintrustFiniteDecimal $p.Value $FieldPath }
function Get-BraintrustRequiredJsonInteger { param([Parameter(Mandatory=$true)][object]$Object,[Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][Alias('FieldName')][string]$FieldPath) $v=Get-BraintrustRequiredJsonFiniteNumber $Object $Name $FieldPath; if([decimal]::Truncate($v)-ne$v){throw "JSON field '$FieldPath' must be an integer."}; return $v }
